name: Deploy to Virtual Server

on:
  push:
    branches:
      - master  # デプロイ対象のブランチ

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Deploy to server
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "
          mkdir -p /var/www/chat-agent && \
          rm -rf /var/www/chat-agent/*"
        scp -o StrictHostKeyChecking=no -r ./* ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/var/www/chat-agent/
        ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "
          chmod +x /var/www/chat-agent/start_streamlit.sh && \
          pkill -f streamlit || true && \
          nohup /var/www/chat-agent/start_streamlit.sh > /var/www/chat-agent/streamlit.log 2>&1 &"
